# Generated by Django 6.0.3 on 2026-03-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cgpa',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='dob',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(default='Not specified', max_length=10),
            preserve_default=False,
        ),
    ]
