# Generated by Django 6.0.3 on 2026-03-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_cgpa_application_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='college',
            new_name='institute_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='application',
            name='year',
        ),
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='course_duration',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='course_name',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='highest_degree',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='institute_address',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='prev_cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='prev_department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='prev_institute',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='prev_institute_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='prev_specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='specialization',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='state',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='tenth_percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='twelfth_percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
