# Generated by Django 6.0.3 on 2026-03-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_rename_college_application_institute_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
