# Generated by Django 6.0.3 on 2026-04-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_add_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='scheme',
            field=models.CharField(choices=[('', '-- Select Scheme --'), ('Project/Thesis', 'Project / Thesis'), ('Internship', 'Internship')], default='Internship', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], default='Mr', max_length=5),
        ),
    ]
