# Generated by Django 6.0.4 on 2026-05-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_application_admin_notes_application_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
