# Generated by Django 6.0.4 on 2026-05-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
