# Generated by Django 6.0.4 on 2026-05-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_project_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attendance_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
